export default {
    GET_CITIES: 'GET_CITIES',
    GET_CITIES_SEARCH_RESULT: 'GET_CITIES_SEARCH_RESULT',
    ADD_CITY: 'ADD_CITY',
    GET_SELECTED_CITY: 'GET_SELECTED_CITY',
    UPDATE_CITY: 'UPDATE_CITY',
    DELETE_CITY: 'DELETE_CITY'
}